feat: создаём базовый функционал
pol-yap/java-filmorate pull request #1
Opened 2022-08-07 07:05 UTC by pol-yap

2022-08-07 18:52 UTC, FanaticFiz requested changes

2022-08-07 18:52 UTC, FanaticFiz commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Ну что же, начнем с многоуважаемого `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Хорошим тоном будет указание кодировки в properties `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-08-07 18:52 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после не стесняйся - смело проставь версию!

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +package ru.yandex.practicum.filmorate.controllers;
Приди к единому и однообразному именованию пакетов.
Как ты считаешь нужным, именовать во множественном числе или единственном. 

У тебя сейчас `contollers`, но `model`

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            user.setName(user.getLogin());
В одной работе я уже это встречал... 
Валидатор должен только валидировать, а у тебя тут еще и бизнес логика.

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        log.trace("Создан новый пользователь {}", user);
trace это самый последний и полный лог, тут уместнее debug или info

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/errors/WrongDataException.java
> +public class WrongDataException extends RuntimeException{
Принято назвать этот ексепшн: BadRequestException

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Ты вроде и подключил валидацию, но не используешь её тут, а написал вручную те проверки которые могут быть покрыты простыми аннотациями.
Например максимальная длинна `description`

2022-08-07 18:52 UTC, FanaticFiz commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate.controllers=trace
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате yaml -> application.yml

Соответственно - попрошу тебя этому следовать.
Как мини задание: разберись как задать порт для сервиса отличный от дефолтного, и как задать чтобы порт был случайным.
(Менять порт на другой не нужно, для тестов нужен именно 8080)

2022-08-07 19:02 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            user.setName(user.getLogin());
Ну, тут как бы с одной стороны бизнес-логика, да, но с другой -- это изменение некорректно заданного поля. Это не возражение. скорее объяснение. Вынесу в отдельный метод

2022-08-07 19:02 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/errors/NotFoundException.java
> +package ru.yandex.practicum.filmorate.controllers.errors;
Почему название пакета не `exception/exceptions` ?

2022-08-07 19:03 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        log.trace("Создан новый пользователь {}", user);
А TRACE тогда для чего? Я так понял из лекций, что INFO это про общее состояние приложения. А вот такие мелочи, это и не дебаг даже..

2022-08-07 19:05 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Столкнулся с тем, что не работает аннотация @Past, например. Пришлось руками написать

2022-08-07 19:08 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +package ru.yandex.practicum.filmorate.controllers;
Думал, что  model -- это типа модель предметной области, она одна

2022-08-08 09:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +package ru.yandex.practicum.filmorate.controllers;
Если у тебя `model` это M из MVC то просто ниже будет еще разделение и вот эти классы что у нас сейчас есть это `entities`. Но давай пока на этом не заострять внимание, с развитием проекта эта тема станет более раскрываться...

2022-08-08 09:23 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        log.trace("Создан новый пользователь {}", user);
"А TRACE тогда для чего?" - а я же с этого и начал ))
"trace это самый последний и полный лог" - вот поиграйся с изменением уровня логирования, ты увидишь сколько инфы вываливается в trace. Ты там свои логи не найдешь. ))

2022-08-08 09:24 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Ну да это место стоит вручную проработать...

2022-08-08 09:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/exceptions/BadRequestException.java
> +public class BadRequestException extends RuntimeException{
Надо подкрутить настройки, вот тут: `RuntimeException{` должен быть пробел
`RuntimeException {`

2022-08-08 09:28 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Разобрался. На самом деле тупо звбыл @Valid написать. Сейчас почти всё убрал в аннотации

2022-08-08 15:11 UTC, merged