feat: хранение данных в H2, рейтинг MPAA, жанры, невзаимная дружба, O…
pol-yap/java-filmorate pull request #5
Opened 2022-09-09 09:04 UTC by pol-yap

…ptional вместо сущностей

2022-09-09 21:09 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/resources/application.yml
> +
называй файлы в ресурсах однообразно, это я про `Filmorate.png -> filmorate.png`

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS MPAA_ratings(
Именовать таблицы в БД принято в нижнем регистре.
`mpaa` это и есть аббревиатура рейтинговой ассоциации, это я к тому что добавление `ratings` тут ни к чему.

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS Friendship(
А как у тебя организовано подтверждение дружбы?
Вот если было бы доп поле типа boolean `confirmed`...

Т.е. один послал запрос, создалась запись (`confirmed: false`), и только когда второй подтвердил ставится статус `confirmed: true`

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film findById(@PathVariable int filmId) { return service.findById(filmId);  }
Чего скукожились в одну строку?
Это нифига не воспринимается глазами, это не удобно читать, а код читают гораздо чаще чем пишут!
Сэкономили одну строку?

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +@RequestMapping("/mpa")
А в таблице я видел правильное название рейтинга: `mpaa`, а `mpa` это уже чтот другое ))

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +public class MPAController {
Не корректно с точки зрения naming convention. `MpaaController`
`XmlSome` `JsonSome` всё как верблюд завещал! )

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +        return service.update(mpa.getId(), mpa);
Ну и зачем, спрашивается, вытаскивать из сущности id и передавать отдельно, когда следом идёт полная сущность??

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Size(max=MAX_DESCRIPTION_LENGTH)
Здаётся мне что описание полей тут и в БД различаются... 
Я имею ввиду размер строки. Тут ты пишешь что `description` у тебя длинной `200` символов.
А в БД ?
А в БД ты ничего не проставил, а значит по умолчанию 255.

За этим надо внимательно следить...
И кстати так себе значение для описания, ну т.е. ооочень маловато.

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private MPA mpa;
Очень ТЕСНО ! 
Между полями пустая строка должна быть...

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("filmDBStorage")
`filmDBStorage -> filmDbStorage`

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/MPAService.java
> +                      .orElseThrow(()->new NotFoundException(id, "рейтинг MPAA"));
Я смотрю тебе понравился `Optional`, поддерживаю!

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public interface GenreStorage {
Ты же видишь сходство между интерфейсами, не чувствуешь в себе силы сделать с этим что-то?

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>  public interface FilmStorage {
Должен быть реализован полные CRUD для UserStorage, FilmStorage
Т.е. у тебя не хватает удаления по id

А для GendeDbStorage, MpaDbStorage - только getById + getAll

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDBStorage.java
> +                           .peek(this::loadGenres)
Получать список жанров необходимо через сервис.
Сейчас получается что при выборке 100 фильмов одним запросом ты сделаешь еще 100 запросов на жанры. 
Это классический случай `N + 1 проблемы`.

Чтобы этого избежать ты тут связанные сущности не достаешь. 
А делаешь это в сервисе, обращаясь к соседним сервисам за нужными данными, так чтобы всё получать одним запросом...

2022-09-09 21:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    void addFriend(final int userId, final int friendId);
Друзья и лайки это самостоятельные таблицы в БД, самостоятельные сущности сейчас у нас...
Поэтому для них свои FriendDbStorage, LikeDbStorage ну и там свои запросы по добавлению и удалению

2022-09-12 09:13 UTC, pol-yap commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS Friendship(
Сначала тоже так сделал, а потом на Q&A поняли, что это избыточно -- дружба подтверждается симметричной записью со стороны друга

2022-09-12 09:14 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film findById(@PathVariable int filmId) { return service.findById(filmId);  }
это не я, это IDEA))

2022-09-12 09:15 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +@RequestMapping("/mpa")
Ничего  не поделаешь -- так в тестах

2022-09-12 09:17 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/service/MPAService.java
> +                      .orElseThrow(()->new NotFoundException(id, "рейтинг MPAA"));
Долго не понимал, зачем они нужны и чем плоха простая проверка на null. Потом понял, что это де-факто стандарт, что-то типа культуры написания кода. Пришлось принять, да)

2022-09-12 15:12 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Size(max=MAX_DESCRIPTION_LENGTH)
Да, правда -- ограничил длину в таблице.
Что же до описания длиной 200 символов -- так было в ТЗ. И даже есть тест, в котором запрос должен валиться при слишком длинном дескрипшене

2022-09-14 19:23 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS Friendship(
В смысле в БД будут две записи вместо одной?
Сомнительно что это лучше одной записи с доп полем...

2022-09-14 19:24 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film findById(@PathVariable int filmId) { return service.findById(filmId);  }
ты должен быть главнее своей IDEA ))

2022-09-14 19:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +@RequestMapping("/mpa")
ну против спецификации не попрешь ))

2022-09-15 21:11 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Ты перепутал при удалении принято отвечать не 404 а 204 `NO_CONTENT`
4-сотые это коды ошибок.

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService service;
`Field injection is not recommended`!

У тебя в контроллере фильмов верно сделано, а в остальных нет...

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +import ru.yandex.practicum.filmorate.service.FriendService;
не используемый импорт...

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Size(max=MAX_DESCRIPTION_LENGTH)
Да, проверяя другую работу я это уже понял. Это учебный проект, пусть будет 200.

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private GenreService genreService;
По всему коду заимпортить через конструктор надо

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public List<Film> findAll() {
Самый главный вопрос был при выборке множества фильмов... 
И тут у тебя нет про жанры ничего. Т.е. при выборке фильма по id жанры приходят, а при findAll нет.
Как тесты прошли я не пойму, не покрыт этот конкретный кейс чтоли...

Да и с отдельными сервисами для жанра и лайков перебор. Можно просто в этом сервисе использовать хранилище жанров. Для загрузки жанров ко всем фильмам.

`genreStorage.load(films);`

Так что этот вопрос не закрыт...

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Ну опять же можно упростить и иметь только два сервиса для фильмов и для пользователей.
А в этих сервисах использовать нужные хранилища.
Например в этом сервисе два хранилища подключить UserStorage storage, FriendStorage friendStorage

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +        //формально тут у нас проблема N+1,
Ну так себе конечно ))
Это учебный сервис и никто и никогда им не воспользуется и ни одного фильма не создаст, но это не должно нам мешать видеть проблемы и учиться их обходить, так ведь?

Хотя да, я не про вставку говорю, просто увидел коммент ))
Нам надо при выборке всех фильмов разобраться...

2022-09-15 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/MpaaDbStorage.java
> +public class MpaaDbStorage extends SimpleDbStorage {
В целом идея с `Simple` понятна...
но на дженериках было бы компактнее везде.
Но давай тогда их пробовать уже в следующей работе.

2022-09-15 21:32 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService service;
А при инжекте через конструктор можно использовать @Qualifier? Я только из-за него привязываю поля напрямую.

2022-09-15 21:37 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public List<Film> findAll() {
Я опирался именно на тесты, когда убирал загрузку жанров во все фильмы из списка. Решил, что это будет оверинжиниринг)) Допишу.
Для жанров есть отдельный контроллер, значит и сервис должен быть, нет?
И вообще идея была всю логику вынести в сервисы, а в хранилищах оставить только работу непосредственно с сущностями. Такой отход от репозиториев в сторону DAO

2022-09-15 21:39 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Есть конкретные отдельные эндпойнты для жанров, рейтингов MPAA... зачем же это всё в сервис для фильмов совать?

2022-09-15 21:42 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +        //формально тут у нас проблема N+1,
Да нет, тут без поправки на учебность. Ну сколько может быть жанров у фильма -- два, три, ну пять. Тут мы работаем с одним фильмом, так что всё ещё не вижу необходимости пихать все жанры в один запрос.

2022-09-15 21:42 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/MpaaDbStorage.java
> +public class MpaaDbStorage extends SimpleDbStorage {
Попытался сначала именно на дженериках. Чот не получилось. Попробую ещё раз.

2022-09-16 13:35 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService service;
можно, поправил))

2022-09-16 18:42 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/MpaaDbStorage.java
> +public class MpaaDbStorage extends SimpleDbStorage {
Попробовал, вроде менее криво получилось. Потом запушу, как разберусь с n+1

2022-09-18 21:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public List<Film> findAll() {
"Решил, что это будет оверинжиниринг" - важно чтобы сущность отдавалась одинаковой в одиночном и множественно представлениях.

2022-09-18 21:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Если нам нужно просто наполнить главную сущность доп. информацией то кажется что нет нужды. 
Как только появиться что-то что выделит эти сущности как самостоятельные, конечно они обзаведутся своими сервисами. 


Но вообще да, нам нужен диалог, который не получается построить тут. 
Давай может ты будешь мне в slack если и не писать вопросы целиком, то хотя бы просто маяковать что ты озвучил вопросы на этой площадке.

2022-09-18 21:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +        //формально тут у нас проблема N+1,
Твои аргументы железны! Я соглашусь что я тут перегибаю палку, просто хотелось заострить твоё внимание на этой проблеме.

2022-09-18 21:26 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +        //формально тут у нас проблема N+1,
В учебных целях засунул эти инсёрты в батч))

2022-09-18 21:27 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Да, как-то здесь обсуждение.. эм... непривычно, как минимум. А то и просто неудобно)

2022-09-18 21:29 UTC, FanaticFiz approved these changes

2022-09-18 21:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Нет ну, то что мы вот продолжаем писать в одном каком то треде, обсуждая именно этот кейс... это удобно.
Просто я например прихожу сюда только тогда когда вижу от тебя пришедший тикет. 
А вот slack регулярно проверяю.

2022-09-18 21:40 UTC, pol-yap commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Ну может.. В общем, по поводу сервисов -- мне кажется логичным правило "каждому контроллеру -- по сервису". Сейчас сделал именно так. А собственные контроллеры для жанров и рейтингов MPAA  -- ну логично же, что должна быть возможность удалить/добавить/переименовать.

2022-09-18 21:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendService.java
> +public class FriendService {
Да, поддерживаю.

2022-09-19 07:44 UTC, merged